name: deploy SPEED
on:
  push:
    branches:
      - jimmy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
      - name: Install Vercel CLI
        run: |
          cd backend 
          npm install --global vercel@latest
      - run: |
          cd backend 
          npm run build --if-present
      - name: Deploy to Vercel
        run: |
          cd backend 
          npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Install frontend Vercel CLI
        run: |
          cd frontend 
          npm install --global vercel@latest
      - name: Deploy frontend to Vercel
        run: |
          cd frontend 
          npx vercel --token ${VERCEL_TOKEN}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
